-- D1 schema for mortgage-compare-app
-- Apply with: wrangler d1 execute mortgage-compare-db --file=src/schema.sql

CREATE TABLE IF NOT EXISTS scenarios (
  id          TEXT    PRIMARY KEY,          -- UUID generated by worker
  device_id   TEXT    NOT NULL,             -- UUID stored in client localStorage
  label       TEXT    NOT NULL DEFAULT '',  -- user-facing name
  inputs_json TEXT    NOT NULL DEFAULT '{}',-- MortgageInputs serialized as JSON
  outputs_json TEXT   NOT NULL DEFAULT '{}',-- MortgageOutputs serialized as JSON
  created_at  INTEGER NOT NULL,             -- Unix epoch seconds
  updated_at  INTEGER NOT NULL              -- Unix epoch seconds
);

CREATE INDEX IF NOT EXISTS idx_scenarios_device_id ON scenarios (device_id);
